# Iteration summary of ceres solver
# See: http://ceres-solver.org/nnls_solving.html#iterationsummary

int64 iteration
bool step_is_valid
bool step_is_nonmonotonic
bool step_is_successful
float64 cost
float64 cost_change
float64 gradient_max_norm
float64 gradient_norm
float64 step_norm
float64 relative_decrease
float64 trust_region_radius
float64 eta
float64 step_size
int64 line_search_function_evaluations
int64 linear_solver_iterations
float64 iteration_time_in_seconds
float64 step_solver_time_in_seconds
float64 cumulative_time_in_seconds