# This message expresses possible proximity pairs.

Header header

# Proximity pairs with their indexes. These are not links but predefined collision objects in the robot configuration header.
uint32[] int_pair_a
uint32[] int_pair_b

# Proximity pairs with their indexes. These are not links but predefined collision objects in the robot configuration header.
uint32[] ext_pair_robot
uint32[] ext_pair_object